# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-test-api

on:
  workflow_dispatch

jobs:
  buildTest:
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x       

    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover -l trx
      working-directory: src

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization="${{ secrets.SONAR_ORGANIZATION }}"
          -Dsonar.projectKey="${{ secrets.PROJECT_KEY }}"
          -Dsonar.cs.opencover.reportPaths=coverage.xml
          -Dsonar.verbose=true
  
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
