name: AmberEggApi Build Test Sonar

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  buildTest:
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x       

    - name: Setup Java
      uses: actions/setup-java@v4.0.0
      with:        
        java-version: 17
        distribution: temurin
        
    - name: Setup SonarCloud Scanner      
      run: dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      working-directory: src

    - name: Test and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      
      run: |
        ./.sonar/scanner/dotnet-sonarscanner begin /k:"${{ secrets.PROJECT_KEY }}" /o:"${{ secrets.SONAR_ORGANIZATION }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.opencover.xml" /d:sonar.exclusions="**.Database/**,**.Tests/**,**.Common*/**"
        
        dotnet test /p:CollectCoverage=true /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx

        ./.sonar/scanner/dotnet-sonarscanner end
      working-directory: src
  
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
