name: Build Test Quality

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build:
    name: BuildTestQuality
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x        
   
    - name: Install dependencies
      run: dotnet restore
      working-directory: src

    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      working-directory: src

    - name: Run tests with coverage
      run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      working-directory: src

    - uses: SonarSource/sonarcloud-github-action@v5.0.0
      with:
        projectBaseDir: src
        args: >
           -Dsonar.host.url="https://sonarcloud.io"
           -Dsonar.organization="${{ secrets.SONAR_ORGANIZATION }}"
           -Dsonar.projectKey="${{ secrets.PROJECT_KEY }}"
           -Dsonar.login="${{ secrets.SONAR_TOKEN }}"                
           -Dsonar.verbose=true
           -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml 
           -Dsonar.test.exclusions="**.Database/**,**.Tests/**,**.WebApi*/**"   
