name: Build Test Quality

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  build:
    name: BuildTestQuality
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x        

    - name: Setup .NET Coverage Tool
      run: dotnet tool install --global dotnet-coverage      

    - name: Build and Test Coverage Gathering
      run: dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'          
      working-directory: src

    - uses: SonarSource/sonarqube-scan-action@v5.3.0
      with:
        projectBaseDir: src
        args: >
          -Dsonar.host.url="https://sonarcloud.io"
          -Dsonar.organization="${{ secrets.SONAR_ORGANIZATION }}"
          -Dsonar.projectKey="${{ secrets.PROJECT_KEY }}"
          -Dsonar.login="${{ secrets.SONAR_TOKEN }}"                
          -Dsonar.verbose=true
          -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml 
          -Dsonar.exclusions="**.Database/**,**.Tests/**,**.WebApi*/**"      
